redis:
  image: redis
  ports:
    - '6379:6379'

flume:
  image: bitwalker/alpine-elixir:1.6.6
  command: elixir --sname flume --cookie flume -S mix run --no-halt
  working_dir: /opt/flume
  environment:
    - FLUME_REDIS_HOST=redis
  volumes:
    - '.:/opt/flume'
  links:
    - redis
