name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 22.1
          elixir-version: 1.8.2
      - name: Install dependencies
        run: mix deps.get --only test
      - name: Check mix format
        run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v1
      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 22.1
          elixir-version: 1.8.2
      - name: Install dependencies
        run: |
          mix deps.get --only test
          mix deps.compile
      - name: Run tests
        run: mix test
        env:
          REDIS_HOST: redis
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
